export const LANGUAGES = [
  { code: 'en', label: 'English' },
  { code: 'am', label: 'አማርኛ (Amharic)' },
  { code: 'om', label: 'Afaan Oromoo' },
  { code: 'ti', label: 'ትግርኛ (Tigrinya)' },
] as const

export type LangCode = typeof LANGUAGES[number]['code']

// Static translations — checked before hitting the API so these are instant and never return garbage
const STATIC: Partial<Record<LangCode, Record<string, string>>> = {
  ti: {
    'City, neighborhood, or address…': 'ከተማ፣ ከባቢ፣ ወይስ ኣድራሻ…',
    'City, address, or sub-city…': 'ከተማ፣ ኣድራሻ ወይስ ክፍለ-ከተማ…',
    'Rent': 'ኪራይ',
    'Buy': 'ዕድጋ',
    'Sort': 'ደርድር',
    'Sort:': 'ደርድር፡',
    'No homes found': 'ቤታት ኣይተረኽባን',
    'Try adjusting your filters or search': 'ማጣሪያታት ወይ ምድላይ ኣስተካኽሉ',
    'Map': 'ካርታ',
    'List': 'ዝርዝር',
    'homes': 'ቤታት',
    'property': 'ቤት',
    'properties': 'ቤታት',
    'Load more homes': 'ዝያዳ ቤታት ጽዓን',
    'Newest': 'ሓዲሽ',
    'Price: Low → High': 'ዋጋ፡ ካብ ትሑት ናብ ልዑል',
    'Price: High → Low': 'ዋጋ፡ ካብ ልዑል ናብ ትሑት',
    'Most Bedrooms': 'ብዙሕ ክፍሊ ምሕዳር',
    'Most Bathrooms': 'ብዙሕ ክፍሊ ሕጽብ',
    'Largest Area': 'ዝዓበየ ቦታ',
    'Filters': 'ማጣሪያታት',
    'Bedrooms': 'ክፍሊ ምሕዳር',
    'Bathrooms': 'ክፍሊ ሕጽብ',
    'Any': 'ዝኾነ',
    'Furnished': 'ዝተሰናደወ',
    'Unfurnished': 'ዘይተሰናደወ',
    'Property Details': 'ዝርዝር ንብረት',
    'About this home': 'ብዛዕባ እዚ ቤት',
    'Amenities': 'ኣገልግሎታት',
    'Type': 'ዓይነት',
    'City': 'ከተማ',
    'Sub-City': 'ክፍለ-ከተማ',
    'Woreda': 'ወረዳ',
    'Kebele': 'ቀበሌ',
    'Landmark': 'ምልክት',
    'Available From': 'ካብ መዓስ ይርከብ',
    'Beds': 'ክፍሊ ምሕዳር',
    'Baths': 'ክፍሊ ሕጽብ',
    'Translate': 'ተርጉም',
    'Show original': 'ናይ መበቆል ኣርኢ',
    'Translating…': 'ይትርጎም ኣሎ…',
    'Report listing': 'ዝርዝር ጸብጻብ ምሃብ',
    'Telegram': 'ቴሌግራም',
    'WhatsApp': 'ዋትስኣፕ',
    'Search': 'ድለ',
    'Saved': 'ዝተቀምጡ',
    'My Home': 'ቤተይ',
    'Profile': 'ፕሮፋይል',
    'Language': 'ቋንቋ',
    'FOR RENT': 'ንኪራይ',
    'FOR SALE': 'ንሽያጥ',
    'No results found. Try adjusting your filters.': 'ውጽኢት ኣይተረኽበን። ማጣሪያታት ኣስተካኽሉ።',
  },
  om: {
    'City, neighborhood, or address…': 'Magaalaa, naannoo, ykn teessoo…',
    'City, address, or sub-city…': 'Magaalaa, teessoo, ykn kutaa magaalaa…',
    'Rent': 'Kiraa',
    'Buy': 'Bituu',
    'Sort': 'Tarreessi',
    'Sort:': 'Tarreessi:',
    'No homes found': 'Manneen hin argamne',
    'Try adjusting your filters or search': 'Fiilteroota ykn barbaaduu sirreessuu yaalaa',
    'Map': 'Kaartaa',
    'List': 'Tarree',
    'homes': 'Manneen',
    'property': 'Mana',
    'properties': 'Manneen',
    'Load more homes': 'Manneen dabalaa fe\'i',
    'Newest': 'Haaraa',
    'Price: Low → High': 'Gatii: Gad-aanaarraa Ol-aanaa',
    'Price: High → Low': 'Gatii: Ol-aanaarraa Gad-aanaa',
    'Most Bedrooms': 'Kutaa Ciisichaa Baayee',
    'Most Bathrooms': 'Kutaa Dhiqannaa Baayee',
    'Largest Area': 'Bakka Bal\'aa',
    'Filters': 'Fiilteroota',
    'Bedrooms': 'Kutaa Ciisichaa',
    'Bathrooms': 'Kutaa Dhiqannaa',
    'Any': 'Kamiyyuu',
    'Furnished': 'Meeshaalee Qaba',
    'Unfurnished': 'Meeshaalee Dhabuu',
    'Property Details': 'Bal\'ina Qabeenya',
    'About this home': 'Mana kana waa\'ee',
    'Amenities': 'Tajaajilaalee',
    'Type': 'Gosa',
    'City': 'Magaalaa',
    'Sub-City': 'Kutaa Magaalaa',
    'Woreda': 'Woreedaa',
    'Kebele': 'Keebele',
    'Landmark': 'Mallattoo',
    'Available From': 'Guyyaa argamu',
    'Beds': 'Kutaa Ciisichaa',
    'Baths': 'Kutaa Dhiqannaa',
    'Translate': 'Hiiki',
    'Show original': 'Asaasaa agarsiisi',
    'Translating…': 'Hiikamaa jira…',
    'Report listing': 'Tarree gabaasi',
    'Telegram': 'Teleegiraam',
    'WhatsApp': 'WhatsApp',
    'Search': 'Barbaadi',
    'Saved': 'Kuufame',
    'My Home': 'Mana koo',
    'Profile': 'Profaayilii',
    'Language': 'Afaan',
    'FOR RENT': 'KIREEFFACHUUF',
    'FOR SALE': 'GURGURAMUUF',
    'No results found. Try adjusting your filters.': 'Bu\'aan hin argamne. Fiilteroota sirreessuu yaalaa.',
  },
  am: {
    'City, neighborhood, or address…': 'ከተማ፣ አካባቢ ወይም አድራሻ…',
    'City, address, or sub-city…': 'ከተማ፣ አድራሻ ወይም ክፍለ-ከተማ…',
    'Rent': 'ኪራይ',
    'Buy': 'ግዢ',
    'Sort': 'ደርድር',
    'Sort:': 'ደርድር፡',
    'No homes found': 'ምንም ቤቶች አልተገኙም',
    'Try adjusting your filters or search': 'ማጣሪያዎቹን ወይም ፍለጋውን ያስተካክሉ',
    'Map': 'ካርታ',
    'List': 'ዝርዝር',
    'homes': 'ቤቶች',
    'property': 'ቤት',
    'properties': 'ቤቶች',
    'Load more homes': 'ተጨማሪ ቤቶች ጫን',
    'Newest': 'አዲሱ',
    'Price: Low → High': 'ዋጋ፡ ከዝቅ ወደ ከፍ',
    'Price: High → Low': 'ዋጋ፡ ከከፍ ወደ ዝቅ',
    'Most Bedrooms': 'ብዙ መኝታ ቤቶች',
    'Most Bathrooms': 'ብዙ መታጠቢያ ቤቶች',
    'Largest Area': 'ትልቁ ቦታ',
    'Filters': 'ማጣሪያዎች',
    'Bedrooms': 'መኝታ ቤቶች',
    'Bathrooms': 'መታጠቢያ ቤቶች',
    'Any': 'ማንኛውም',
    'Furnished': 'የተሰናዳ',
    'Unfurnished': 'ያልተሰናዳ',
    'Property Details': 'የቤቱ ዝርዝር',
    'About this home': 'ስለዚህ ቤት',
    'Amenities': 'አገልግሎቶች',
    'Type': 'አይነት',
    'City': 'ከተማ',
    'Sub-City': 'ክፍለ-ከተማ',
    'Woreda': 'ወረዳ',
    'Kebele': 'ቀበሌ',
    'Landmark': 'መለያ',
    'Available From': 'ከመቼ ጀምሮ ይገኛል',
    'Beds': 'መኝታ',
    'Baths': 'መታጠቢያ',
    'Translate': 'ተርጉም',
    'Show original': 'ዋናውን አሳይ',
    'Translating…': 'እየተተረጎመ ነው…',
    'Report listing': 'ዝርዝር ሪፖርት ያድርጉ',
    'Telegram': 'ቴሌግራም',
    'WhatsApp': 'ዋትስኣፕ',
    'Search': 'ፈልግ',
    'Saved': 'የተቀመጡ',
    'My Home': 'ቤቴ',
    'Profile': 'መገለጫ',
    'Language': 'ቋንቋ',
    'FOR RENT': 'ለኪራይ',
    'FOR SALE': 'ለሽያጭ',
    'No results found. Try adjusting your filters.': 'ምንም ውጤት አልተገኘም። ማጣሪያዎቹን ያስተካክሉ።',
  },
}

export async function translateText(text: string, to: LangCode, from: LangCode = 'en'): Promise<string> {
  if (to === from || !text.trim()) return text
  const staticMatch = STATIC[to]?.[text]
  if (staticMatch) return staticMatch
  try {
    const url = `https://api.mymemory.translated.net/get?q=${encodeURIComponent(text)}&langpair=${from}|${to}`
    const res = await fetch(url)
    if (!res.ok) return text
    const data = await res.json() as {
      responseStatus?: number
      responseData?: { translatedText?: string }
    }
    if (data?.responseStatus !== 200) return text
    const translated = data?.responseData?.translatedText?.trim()
    if (!translated || translated === '%' || translated.startsWith('MYMEMORY')) return text
    return translated
  } catch {
    return text
  }
}
